# Generated by Django 6.1.1 on 2026-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('verdict', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
