# Generated by Django 5.2.18 on 2026-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
